name: lint

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches: [main]

jobs:
  fmt:
    name: fmt
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: install rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          components: rustfmt clippy
      - name: run fmt
        run: cargo +nightly fmt --all -- --check
      - name: run clippy
        run: cargo clippy --workspace --all-features -- -D warnings
      - name: install udeps
        run: cargo install --git https://github.com/est31/cargo-udeps --locked
      - name: run udeps
        run: cargo +nightly udeps
      - name: Run CodeSpell
        uses: codespell-project/actions-codespell@v2.0
        with:
          check_hidden: true
          check_filenames: true
          skip: .git,Cargo.lock,target,CHANGELOG.md
          ignore_words_list: crate,Crate,functio
